### ISSUE TITLE
Test Running Server on MacOS (or Linux)

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#12]
Need to investigate running the server from source on MacOS or Linux.

It should work fine, but need to double-check.

**Comment by g-liu** [comment]
I have downloaded the source code to run the server on Mac OS X running Yosemite. After installing all required dependencies, I run `python SBA_Serv.py` and it reports the following:

<pre>
geoff:SBA_Serv geoff$ python SBA_Serv.py
Loading chipmunk for Darwin (64bit) [/Library/Python/2.7/site-packages/pymunk/libchipmunk.dylib]
Usage: SBA_Serv.py [options] [config_file] [more_config_files...]
You should pass at least one config file to the server. Additional config files will override/add to the options in the base file.
Options:
  -h, --help            show this help message and exit
  -n, --nolog           turns logging off
  -v, --verbose         turns logging to DEBUG (from INFO)
  -l LOGFILENAME, --logfile=LOGFILENAME
                        specifies the file to log info to
---
It is recommended to run Space Battle Arena with customized configuration.
See http://mikeware.github.io/SpaceBattleArena/server
---
Logging to SBA_Serv2015-08-02_155616.log Verbose: False
Loaded Default Configuration
Attempting to Load Game:  Basic
Initializing cpSpace - Chipmunk v6.2.0 (Debug Enabled)
Compile with -DNDEBUG defined to disable debug mode and runtime assertion checks
Game:  <Game.Game.BasicGame object at 0x10ac08d90>
Traceback (most recent call last):
  File "SBA_Serv.py", line 146, in <module>
    server = WorldServer.WorldServer(cfg.getint("Server", "port"), game)
  File "/Users/geoff/Documents/GitHub/SBA_Serv/Server/WorldServer.py", line 25, in __init__
    print "Server Started at IP: " + Server.MWNL2.getIPAddress()
  File "/Users/geoff/Documents/GitHub/SBA_Serv/Server/MWNL2.py", line 22, in getIPAddress
    return socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
</pre>

It appears that getting IP address is not working. So in `MWNL2.py`, I change line 22 to:

<pre>
return "192.168.1.104"
</pre>

which is my actual IP address. After that, another error:

<pre>
Server Started at IP: 192.168.1.104
Traceback (most recent call last):
  File "SBA_Serv.py", line 154, in <module>
    main.startGame(titlever + title_game, game, cfg.getboolean("Application", "fullscreen"), resolution, cfg.getboolean("Application", "showstats"), cfg.getboolean("Application", "sound"))
  File "/Users/liuyan/Documents/GitHub/SBA_Serv/GUI/main.py", line 232, in startGame
    obj.draw(worldsurface, flags)
  File "/Users/liuyan/Documents/GitHub/SBA_Serv/GUI/ObjWrappers/NebulaWrapper.py", line 20, in draw
    rotimg = Cache().getRotatedImage(self._imageName, math.degrees(-self._worldobj.body.angle))
  File "/Users/liuyan/Documents/GitHub/SBA_Serv/GUI/GraphicsCache.py", line 41, in getRotatedImage
    image = self.getImage(key)
  File "/Users/liuyan/Documents/GitHub/SBA_Serv/GUI/GraphicsCache.py", line 29, in getImage
    self.__cache[key][0] = pygame.image.load(self.__rootdir + key + self.__ext).convert_alpha()
error: Couldn't open GUI/Graphics/Nebula\Nebula384x256.png
Sending Disconnect...
Server Closed, Checking Threads...........Done!
MainThread:<_MainThread(MainThread, started 140735236612864)>
WorldMap_gameloop_<World.WorldMap.GameWorld object at 0x108e75bd0>:<Thread(WorldMap_gameloop_<World.WorldMap.GameWorld object at 0x108e75bd0>, started 4449361920)>
</pre>

The backslash in `GUI/Graphics/Nebula\Nebula384x256.png` looks suspicious, i.e. a Windows-only thing. I go into `NebulaWrapper.py` and change line 14 to use a forward-slash instead. In `Star.py` I also change line 6 to

<pre>
SURFACE = pygame.image.load("GUI/Graphics/Backgrounds/stars.png")
</pre>

At this point, a PyGame window opens and seems to draw all graphics correctly. However I cannot connect any ships to my IP. The complete log:

<pre>
Connecting to 192.168.1.104
Server connection failed.
Connection refused
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:211)
    at ihs.apcs.spacebattle.TextClient.run(TextClient.java:111)
    at ihs.apcs.spacebattle.TextClient.main(TextClient.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Attempting to disconnect...
Shutting down...
Attempting to disconnect...
Exception in thread "main" java.lang.NullPointerException
    at ihs.apcs.spacebattle.TextClient.disconnect(TextClient.java:233)
    at ihs.apcs.spacebattle.TextClient.run(TextClient.java:149)
    at ihs.apcs.spacebattle.TextClient.main(TextClient.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Exception in thread "Thread-0" java.lang.NullPointerException
    at ihs.apcs.spacebattle.TextClient.disconnect(TextClient.java:233)
    at ihs.apcs.spacebattle.networking.ShutdownHook.run(ShutdownHook.java:24)
Process finished with exit code 1
</pre>

My hunch here is that the server was not actually connected to any IP address. Up above where I changed `getIPAddress` in `MWLN2.py`, I probably did not have the right IP. However, `return socket.gethostbyname(socket.gethostname())` throws an error when I run the server.

**Comment by hawkerm** [comment]
Hey Geoffrey,

Thanks for all the detailed info!  Thought I had gotten all the slashes for the images, but that's an easy fix.

Certainly seems like the Python socket calls are working a bit differently in the Mac environment.  I'll have to do some research and figure out a solution.  My main issue is not having access to a Mac for debugging.

Because you're using your network IP though (instead of something like 127.0.0.1 or localhost), I'm wondering if the port is just not open on the Mac firewall, and thus is getting blocked when Java is trying to connect to your server (even though it's on the same box).  Might be a couple of quick things you could look at to see if opening the port or changing the hostname makes any difference.

Thanks again,
- Michael

**Comment by hawkerm** [comment]
We have [official build instructions](https://github.com/Mikeware/SpaceBattleArena/blob/master/SBA_Serv/README.md) for Mac now.
