### ISSUE TITLE
Issue with LowerEnergyScoop and Dragons

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#132]
EXCEPTION IN GAMELOOP

Traceback (most recent call last):

  File "World\WorldMap.pyo", line 231, in __THREAD__gameloop

  File "World\WorldEntities.pyo", line 104, in update

  File "World\Commanding.pyo", line 106, in update

  File "World\WorldCommands.pyo", line 527, in execute

AttributeError: 'Dragon' object has no attribute 'pull'

**Comment by hawkerm** [comment]
Rescoped command to only look at Nebula, BlackHoles and Stars.
