### ISSUE TITLE
Error while trying to Spawn Bauble b1122

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#133]
2016-06-02 08:26:28,984|545014|INFO|Client Receiving Thread 33|WorldServer|171|__serverCallback|Ship Queue Before #721 CommandSystem(deque([], maxlen=4))
2016-06-02 08:26:28,987|545017|INFO|Client Receiving Thread 33|WorldServer|182|__serverCallback|Ship Queue After #721 CommandSystem(deque([Command(#721, STEER, 15, True, 0) DEG: -19], maxlen=4))
2016-06-02 08:26:29,352|545382|INFO|<bound method TheHungerBaublesGame.__cornucopia_bauble_spawn of <Game.TheHungerBaubles.TheHungerBaublesGame object at 0x025D84F0>> p=None|TheHungerBaubles|268|__cornucopia_bauble_spawn|Trying to Spawn Bauble in Cornucopia
2016-06-02 08:26:29,358|545388|INFO|<bound method TheHungerBaublesGame.__cornucopia_bauble_spawn of <Game.TheHungerBaubles.TheHungerBaublesGame object at 0x025D84F0>> p=None|TheHungerBaubles|294|__cornucopia_bauble_spawn|Spawned Bauble in Cornucopia #729 with value 5 and weight 3
2016-06-02 08:26:29,358|545388|ERROR|MainThread|main|675|startGame|FATAL Error in GUI!!!
Traceback (most recent call last):
  File "GUI\main.pyo", line 258, in startGame
  File "Game\BaubleGame.pyo", line 80, in draw
error: Surfaces must not be locked during blit
2016-06-02 08:26:29,358|545388|ERROR|MainThread|main|676|startGame|Traceback (most recent call last):
  File "GUI\main.pyo", line 258, in startGame
  File "Game\BaubleGame.pyo", line 80, in draw
error: Surfaces must not be locked during blit

2016-06-02 08:26:29,359|545389|INFO|MainThread|main|680|startGame|GUI Closed
2016-06-02 08:26:29,362|545392|INFO|MainThread|SBA_Serv|171|<module>|Server Request Disconnect All
2016-06-02 08:26:29,364|545394|INFO|Close All Clients Thread|MWNL2|182|__close|Sending Disconnect Message

**Comment by hawkerm** [comment]
Couldn't see an obvious issue, it was on the call to blit to the surface, so some pygame funkyness going on with some other thread...?

@wortzmanb let me know if that other crash from yesterday was the same or not.  I need more info to act on this bug.

**Comment by hawkerm** [comment]
Have no idea what is locking a surface in pygame.  It could be some shared surface reference issue with the scaled bauble, or something random with the main surface (though the latter seems less likely to always be on the bauble one).
