### ISSUE TITLE
Need to test running tournaments on subgames.

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#53]
Game:  <Game.FindTheMiddle.FindTheMiddleGame object at 0x00D67890>
Server Started at IP: 10.104.213.30
Traceback (most recent call last):
  File "SBA_Serv.py", line 147, in <module>
  File "GUI\main.pyo", line 249, in startGame
  File "Game\FindTheMiddle.pyo", line 101, in gui_draw_game_world_info
AttributeError: 'list' object has no attribute 'values'

**Comment by hawkerm** [comment]
Looks like a specific issue to Find The Middle, will fix that issue, but leave this item as a work item for writing more unit tests around tournaments.
