### ISSUE TITLE
Write Test Case for Disconnect Crash

### ISSUE THREAD

**Issue by hawkerm** [Mikeware/SpaceBattleArena#68]
Should be mitigated by new auto-kick work done in #63.

Repro Kill ship after hard disconnect (in Bauble Hunt)…

```
EXCEPTION IN GAMELOOP
Traceback (most recent call last):
  File "I:\code\SpaceBattleArena\master\SBA_Serv\World\WorldMap.py", line 240, i
n __THREAD__gameloop
    item.removeFromSpace(self.__space)
  File "I:\code\SpaceBattleArena\master\SBA_Serv\World\Entities.py", line 99, in
 removeFromSpace
    space.remove(self.shape, self.body)
  File "C:\Python27\lib\site-packages\pymunk\__init__.py", line 300, in remove
    self._remove_shape(o)
  File "C:\Python27\lib\site-packages\pymunk\__init__.py", line 343, in _remove_
shape
    del self._shapes[shape._hashid_private]
KeyError: 27L
```

Appears we may be just removing the object before we've added it.  Need to try and write a unit test that repros this and test just swapping my ordering.

**Comment by hawkerm** [comment]
Haven't written explicit test case for this yet, but verified through debugger that there was indeed an object queued to be both added and removed.

Made change and will just verify that existing test cases pass and drop private to test.
